/*
 * drum_machine.c — 808 Drum Machine for RP2350
 *
 * Real audio samples via samples.c / samples.h (generated by wav_to_c.py):
 *   kicks01   -> key 1
 *   snare01   -> key 2
 *   hihats05  -> key 3
 *   clap02    -> key 4
 *   cowbell5  -> key 5
 *   ride1     -> key 6
 *   tom1      -> key 7
 *
 * Key bindings:
 *   1-7   live trigger drum + select for step-edit
 *   8     cycle step bank (0->1->2->3->0, each bank = steps bank*4..bank*4+3)
 *   9     Play / Stop
 *   0     BPM + 10
 *   *     BPM - 10
 *   #     Clear current pattern
 *   A-D   toggle step (bank*4 + 0..3) for selected drum
 */

#include <stdio.h>
#include <string.h>
#include "pico/stdlib.h"
#include "hardware/pwm.h"
#include "hardware/clocks.h"
#include "hardware/timer.h"
#include "support.h"    /* RATE */
#include "queue.h"      /* KeyEvents kev, key_push(), key_pop() */
#include "samples.h"    /* generated by wav_to_c.py */

void keypad_init_pins(void);
void keypad_init_timer(void);

#define AUDIO_PIN   36
#define AUDIO_SLICE (8u + (((AUDIO_PIN) >> 1u) & 3u))
#define AUDIO_CHAN  ((AUDIO_PIN) & 1u)

#define NUM_DRUMS    7
#define NUM_STEPS   16
#define NUM_PATTERNS 4
#define DEFAULT_BPM 120
#define MIN_BPM      60
#define MAX_BPM     200

#define DRUM_KICK    0
#define DRUM_SNARE   1
#define DRUM_HIHAT   2
#define DRUM_CLAP    3
#define DRUM_COWBELL 4
#define DRUM_RIDE    5
#define DRUM_TOM     6

/*
 * Samples from wav_to_c.py are uint16_t, range 0..65535, silence=32768.
 * buf is const — points directly into flash, no RAM copy needed.
 */
typedef struct {
    const uint16_t   *buf;
    uint32_t          len;
    volatile uint32_t pos;
    volatile bool     active;
} DrumVoice;

static DrumVoice voices[NUM_DRUMS];

static bool    pat[NUM_PATTERNS][NUM_DRUMS][NUM_STEPS];
static uint8_t current_pat  = 0;
static uint8_t current_step = 0;
static bool    seq_playing  = false;
static int     bpm          = DEFAULT_BPM;
static uint8_t edit_drum    = DRUM_KICK;
static uint8_t step_bank    = 0;  /* 0-3, A-D map to steps bank*4..bank*4+3 */

/* non-blocking key_pop — queue.c's version blocks with sleep_ms(10) */
extern KeyEvents kev;

static bool key_pop_nb(uint16_t *out) {
    if (kev.head == kev.tail) return false;
    *out = kev.q[kev.tail];
    kev.tail = (kev.tail + 1) % 32;
    return true;
}

/* ── init voices pointing at flash arrays ────────────────────────────── */

static void init_drums(void) {
    voices[DRUM_KICK]    = (DrumVoice){ kicks01,  kicks01_len,  0, false };
    voices[DRUM_SNARE]   = (DrumVoice){ snare01,  snare01_len,  0, false };
    voices[DRUM_HIHAT]   = (DrumVoice){ hihats05, hihats05_len, 0, false };
    voices[DRUM_CLAP]    = (DrumVoice){ clap02,   clap02_len,   0, false };
    voices[DRUM_COWBELL] = (DrumVoice){ cowbell5, cowbell5_len, 0, false };
    voices[DRUM_RIDE]    = (DrumVoice){ ride1,    ride1_len,    0, false };
    voices[DRUM_TOM]     = (DrumVoice){ tom1,     tom1_len,     0, false };
}

/*
 * PWM AUDIO ISR
 * Samples are uint16_t 0..65535, silence=32768.
 * Subtract 32768 to centre, average active voices, re-add 32768,
 * then scale to PWM top with the same formula as the original synth:
 *     samp = samp * top / (1<<16)
 */
void pwm_audio_handler(void) {
    uint slice = AUDIO_SLICE;
    pwm_hw->intr = 1ul << slice;

    int32_t mix   = 0;
    int     count = 0;

    for (int d = 0; d < NUM_DRUMS; d++) {
        if (!voices[d].active) continue;
        mix += (int32_t)voices[d].buf[voices[d].pos] - 32768;
        voices[d].pos++;
        if (voices[d].pos >= voices[d].len) {
            voices[d].active = false;
            voices[d].pos    = 0;
        }
        count++;
    }

    uint32_t samp;
    if (count == 0) {
        samp = 32768;
    } else {
        mix /= count;
        mix += 32768;
        if (mix < 0)     mix = 0;
        if (mix > 65535) mix = 65535;
        samp = (uint32_t)mix;
    }

    samp = samp * pwm_hw->slice[slice].top / (1ul << 16);

    hw_write_masked(
        &pwm_hw->slice[slice].cc,
        samp << (AUDIO_CHAN ? PWM_CH0_CC_B_LSB : PWM_CH0_CC_A_LSB),
        AUDIO_CHAN ? PWM_CH0_CC_B_BITS : PWM_CH0_CC_A_BITS
    );
}

/* PWM INIT — identical to your init_pwm_audio() */
static void init_pwm_audio(void) {
    uint slice   = AUDIO_SLICE;
    uint channel = AUDIO_CHAN;

    gpio_set_function(AUDIO_PIN, GPIO_FUNC_PWM);
    pwm_set_clkdiv(slice, 150);
    pwm_hw->slice[slice].top = ((clock_get_hz(clk_sys) / 150) / RATE) - 1;

    hw_write_masked(
        &pwm_hw->slice[slice].cc,
        ((uint)0) << (channel ? PWM_CH0_CC_B_LSB : PWM_CH0_CC_A_LSB),
        channel ? PWM_CH0_CC_B_BITS : PWM_CH0_CC_A_BITS
    );
    hw_write_masked(
        &pwm_hw->slice[slice].csr,
        1ul << PWM_CH0_CSR_EN_LSB,
        PWM_CH0_CSR_EN_BITS
    );

    pwm_hw->intr = 1u << slice;
    pwm_irqn_set_slice_enabled(0, slice, true);
    pwm_set_irq_enabled(slice, true);
    irq_set_exclusive_handler(PWM_IRQ_WRAP_0, pwm_audio_handler);
    irq_set_enabled(PWM_IRQ_WRAP_0, true);
}

/* write pos=0 before active=true so ISR never reads stale pos */
static void play_drum(uint8_t d) {
    if (d >= NUM_DRUMS) return;
    voices[d].pos    = 0;
    voices[d].active = true;
}

/* SEQUENCER TICK — step_us = 60_000_000 / bpm / 4 (sixteenth notes) */
static uint32_t last_step_us = 0;

static void seq_tick(void) {
    if (!seq_playing) return;
    uint32_t now     = timer_hw->timerawl;
    uint32_t step_us = 15000000u / (uint32_t)bpm;
    if ((now - last_step_us) < step_us) return;
    last_step_us = now;
    for (int d = 0; d < NUM_DRUMS; d++)
        if (pat[current_pat][d][current_step]) play_drum(d);
    current_step = (current_step + 1) % NUM_STEPS;
}

/* KEY PROCESSING */
static void process_keys(void) {
    uint16_t ev;
    while (key_pop_nb(&ev)) {
        if (!(ev & 0x100)) continue;
        char key = (char)(ev & 0xFF);
        switch (key) {
            case '1': play_drum(DRUM_KICK);    edit_drum = DRUM_KICK;    break;
            case '2': play_drum(DRUM_SNARE);   edit_drum = DRUM_SNARE;   break;
            case '3': play_drum(DRUM_HIHAT);   edit_drum = DRUM_HIHAT;   break;
            case '4': play_drum(DRUM_CLAP);    edit_drum = DRUM_CLAP;    break;
            case '5': play_drum(DRUM_COWBELL); edit_drum = DRUM_COWBELL; break;
            case '6': play_drum(DRUM_RIDE);    edit_drum = DRUM_RIDE;    break;
            case '7': play_drum(DRUM_TOM);     edit_drum = DRUM_TOM;     break;

            case '8':
                step_bank = (step_bank + 1) % 4;
                printf("Bank %d  (steps %d-%d)\n",
                       step_bank, step_bank*4, step_bank*4+3);
                break;

            case '9':
                seq_playing = !seq_playing;
                if (seq_playing) {
                    current_step = 0;
                    last_step_us = timer_hw->timerawl;
                    printf("PLAY  bpm=%d  pat=%d\n", bpm, current_pat);
                } else {
                    printf("STOP\n");
                }
                break;

            case '0':
                bpm = (bpm + 10 > MAX_BPM) ? MAX_BPM : bpm + 10;
                printf("BPM -> %d\n", bpm);
                break;

            case '*':
                bpm = (bpm - 10 < MIN_BPM) ? MIN_BPM : bpm - 10;
                printf("BPM -> %d\n", bpm);
                break;

            case '#':
                memset(pat[current_pat], 0, sizeof(pat[current_pat]));
                printf("Pattern %d cleared\n", current_pat);
                break;

            case 'A': case 'B': case 'C': case 'D': {
                int offset = (key=='A')?0:(key=='B')?1:(key=='C')?2:3;
                int step   = step_bank * 4 + offset;
                pat[current_pat][edit_drum][step] ^= true;
                printf("drum=%d  step=%2d  %s\n", edit_drum, step,
                       pat[current_pat][edit_drum][step] ? "ON " : "OFF");
                break;
            }

            default: break;
        }
    }
}

/* DEFAULT PATTERN */
static void load_default_pattern(void) {
    pat[0][DRUM_KICK][0]  = pat[0][DRUM_KICK][4]  = true;
    pat[0][DRUM_KICK][8]  = pat[0][DRUM_KICK][12] = true;
    pat[0][DRUM_SNARE][4] = pat[0][DRUM_SNARE][12]= true;
    for (int s = 0; s < NUM_STEPS; s += 2) pat[0][DRUM_HIHAT][s] = true;
    pat[0][DRUM_CLAP][8]    = true;
    pat[0][DRUM_COWBELL][2] = pat[0][DRUM_COWBELL][10] = true;
    pat[0][DRUM_RIDE][0]    = pat[0][DRUM_RIDE][4]     = true;
    pat[0][DRUM_RIDE][8]    = pat[0][DRUM_RIDE][12]    = true;
    pat[0][DRUM_TOM][14]    = pat[0][DRUM_TOM][15]     = true;
}

int main(void) {
    stdio_init_all();
    printf("808 Drum Machine — RP2350\n");

    init_drums();
    init_pwm_audio();
    printf("PWM ready  GPIO=%d  RATE=%d\n", AUDIO_PIN, RATE);

    keypad_init_pins();
    keypad_init_timer();
    printf("Keypad ready\n");

    load_default_pattern();
    printf("1-7=drums  8=bank  9=play/stop  0/*=bpm  #=clear  A-D=steps\n\n");

    for (;;) {
        process_keys();
        seq_tick();
    }
    return 0;
}